image: node:12.13

stages:
  - build
  - publish

build:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build

publish:
  stage: publish
  only:
    - master
  script:
    - git commit -am "update documentation"
    - git push -o ci.skip
    - npm publish


